# Site settings
title: Istoria Municipiului Bacău
# email: your-email@example.com
description: >- 
  Istoria scurtă a municipiului Bacău
baseurl: "/isdv-2023-jud"
url: "https://onefieryfern.github.io"
author: >-
  Florea Andrei, prof. coordonator Crăciun Anca
github_username: onefieryfern

# Build settings
# theme: minima
remote_theme: onefieryfern/minima@snapshot-2023-03-03
minima:
  skin: solarized-light
plugins:
#   - jekyll-feed
