# Site settings
title: Istoria Municipiului Bacău
# email: your-email@example.com
description: >- 
  Istoria Municipiului Bacău
baseurl: "/isdv-2023-jud"
url: "https://onefieryfern.github.io"
github_username: onefieryfern

# Build settings
theme: minima
plugins:
  - jekyll-feed

